### ISSUE TITLE
is possible create a mod type for add better keyboard functionality?

### ISSUE THREAD

**Issue by tsukitaro** [gottyduke/Elin.Plugins#2]
Hi, you work is awesome!

First, is not a mod request

I want to ask you if Elin modding enable to improve keyboard setting with a mod?
I mean, I'm introducing in this mod world I want to know if Elin allow it.

**Comment by gottyduke** [comment]
Hello, yes it's possible, you can achieve basically whatever you want with Harmony & Unity modding.

**Comment by tsukitaro** [comment]
Thank you so much!!
