### ISSUE TITLE
[Question] Compiling

### ISSUE THREAD

**Issue by Verssgn** [gottyduke/Elin.Plugins#3]
Is there a way I could compile the rich presence plugin so I get a usable .dll like you have in the workshop mod? Thanks

**Comment by gottyduke** [comment]
hello, you'll need a .NET compiler, via Visual Studio/Visual Studio Code + dotnet/Rider...etc, setup environment variable `ElinGamePath` to the game's root folder, then load the project ElinRichPresence.csproj and compile it.

**Comment by Verssgn** [comment]
Ok, thank you very much!
